trigger:
- src

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install python3-venv
    python3 -m venv venv
    source venv/bin/activate
    pip3 install setuptools wheel
    pip3 install -r requirements.txt
    venv/bin/pelican ./content -o ./output -s ./publishconf.py 
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git add -f output
    git commit -m 'Publishing output content to Master'
    git push origin src:master
  displayName: 'Make HTML from Pelican source and push to master'

