trigger:
- src

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
  displayName: 'Set Python version to use'

- script: |
    sudo apt install python3-venv
    python3 -m venv venv
    source venv/bin/activate
    pip3 install setuptools wheel
    pip3 install -r requirements.txt
    venv/bin/pelican ./content -o ./output -s ./publishconf.py
    ls -la
  displayName: 'Make HTML from Pelican source'

- publish: $(System.DefaultWorkingDirectory)/output
  artifact: ATN_HTML_OUTPUT
  displayName: 'Publish to Azure Artifacts'

