trigger:
- src

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: pip3 install setuptools wheel
  displayName: 'Install python prereqs'

- script: |
    mkdir venv
    python3 -m venv venv
    source venv/bin/activate
    pip3 install -r requirements.txt
  displayName: 'Make Virtual Environment and install requirements'

- script: |
    make publish
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git add output/
    git commit -m 'Publishing output content to Master'
    git push -u origin master
  displayName: 'Make HTML from Pelican source and push to master'

